version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres


  dbt-postgres:
    image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
    container_name: dbt_postgres_container
    restart: "no"
    depends_on:
      - postgres
    volumes:
      - ./your_dbt_project:./dbt
    environment:
      DBT_ENV_VAR: value
    command: ["sh", "-c", "dbt --version && dbt run && dbt test"]



volumes:
  postgres_data: